"""add class room capacity academic_year

Revision ID: 0ae1f1074418
Revises: 6f41537f70f9
Create Date: 2026-07-17 14:14:21.428731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae1f1074418'
down_revision: Union[str, None] = '6f41537f70f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('room_number', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('academic_year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'academic_year')
    op.drop_column('classes', 'capacity')
    op.drop_column('classes', 'room_number')
    # ### end Alembic commands ###
