"""add teacher contact fields

Revision ID: 3e376d74d49a
Revises: 0ae1f1074418
Create Date: 2026-07-17 14:33:34.568808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e376d74d49a'
down_revision: Union[str, None] = '0ae1f1074418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('teachers', sa.Column('joining_date', sa.Date(), nullable=True))
    op.add_column('teachers', sa.Column('emergency_contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'emergency_contact')
    op.drop_column('teachers', 'joining_date')
    op.drop_column('teachers', 'address')
    op.drop_column('teachers', 'phone')
    # ### end Alembic commands ###
