"""add student extended fields

Revision ID: 6f41537f70f9
Revises: d1a2b3c4e5f6
Create Date: 2026-07-17 13:16:25.308087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f41537f70f9'
down_revision: Union[str, None] = 'd1a2b3c4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('aadhaar_no', sa.String(), nullable=True))
    op.add_column('students', sa.Column('category', sa.String(), nullable=True))
    op.add_column('students', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.add_column('students', sa.Column('allergy_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'allergy_notes')
    op.drop_column('students', 'emergency_contact')
    op.drop_column('students', 'category')
    op.drop_column('students', 'aadhaar_no')
    # ### end Alembic commands ###
