"""add_fees_extended_fields

Revision ID: 71f611741dd9
Revises: 3e376d74d49a
Create Date: 2026-07-17 15:07:11.701966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f611741dd9'
down_revision: Union[str, None] = '3e376d74d49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_structures', sa.Column('late_fee_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('fee_structures', sa.Column('grace_days', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('discount_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'discount_reason')
    op.drop_column('invoices', 'discount_amount')
    op.drop_column('invoices', 'remarks')
    op.drop_column('fee_structures', 'grace_days')
    op.drop_column('fee_structures', 'late_fee_amount')
    # ### end Alembic commands ###
