"""add users auth

Revision ID: a490f8af68ce
Revises: 6cc7a7ab95f6
Create Date: 2026-06-16 16:50:43.598293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a490f8af68ce'
down_revision: Union[str, None] = '6cc7a7ab95f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('password_reset_token_hash', sa.String(), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_foreign_key('profiles_id_fkey', 'profiles', 'users', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_id_fkey', 'profiles', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
